fluent/fluent-plugin-opensearch

.coveralls.yml
.github/workflows/coverage.yaml
Gemfile
README.md
test/helper.rb

Added coveralls settings on GitHubActions.

Upload unit test coverage into coveralls

---

README.md
fluent-plugin-opensearch.gemspec
lib/fluent/plugin/out_opensearch.rb
test/plugin/test_out_opensearch.rb

Closes https://github.com/atomita/fluent-plugin-aws-elasticsearch-service/pull/77
It is reasonable to handle events ingestions of AWS OpenSearch service on fluent-plugin-opensearch it self.

Implement AWS OpenSearch Service Sign request

---

lib/fluent/plugin/out_opensearch_data_stream.rb
test/plugin/test_out_opensearch_data_stream.rb

If the OpenSearch backend is unreachable when the plugin starts its initial configuration, it will crash the Fluentd container (see #7). 
This PR fixes this by adding a retry mechanism to the configuration step, relying on eventual consistency. I did not add a limit to the retry, as the connection should either eventually work, or there is something wrong in the environment that requires manual intervention.

Retry creating data stream/template when OpenSearch is unreachable

---

lib/fluent/plugin/out_opensearch_data_stream.rb
test/plugin/datastream_template.json
test/plugin/test_out_opensearch_data_stream.rb

Signed-off-by: Anders Swanson <anders.swanson@oracle.com>
Currently template_file parameter is not supported by datastream output. This would add creation of index template, it was not working before.

Use template_file for Data Streams

---

lib/fluent/plugin/out_opensearch.rb
test/plugin/test_out_opensearch.rb

Provide suppress_type_name parameter

---

README.OpenSearchInput.md
README.md
lib/fluent/plugin/in_opensearch.rb
lib/fluent/plugin/opensearch_error_handler.rb
lib/fluent/plugin/out_opensearch.rb
lib/fluent/plugin/out_opensearch_data_stream.rb
test/plugin/test_opensearch_error_handler.rb

Related to https://github.com/fluent/fluent-plugin-opensearch/issues/37

Suppress emit error label events

---

lib/fluent/plugin/out_opensearch.rb

Closes https://github.com/fluent/fluent-plugin-opensearch/issues/31

Handle exceptions on retrieving AWS credentials

---

README.md
lib/fluent/plugin/opensearch_error_handler.rb
lib/fluent/plugin/out_opensearch.rb
test/plugin/test_opensearch_error_handler.rb

Related to https://github.com/fluent/fluent-plugin-opensearch/issues/37.

Configurable unrecoverable record types

---

lib/fluent/plugin/opensearch_index_template.rb
lib/fluent/plugin/out_opensearch_data_stream.rb

Automatically create data streams

---

lib/fluent/plugin/out_opensearch_data_stream.rb
test/plugin/test_out_opensearch_data_stream.rb

Closes https://github.com/fluent/fluent-plugin-opensearch/issues/48

opensearch_data_stream: Align lowercases for data_stream and its template names

---

lib/fluent/plugin/opensearch_error_handler.rb
lib/fluent/plugin/out_opensearch.rb

Use if clause to detect requirements for emitting error label events

---

lib/fluent/plugin/out_opensearch.rb
test/plugin/test_out_opensearch.rb

OpenSearch 2 or later seems to be removed type parameter from bulk API:
https://github.com/opensearch-project/OpenSearch/commit/1b571ece28f5644becf97c165de853943af73ac5
Related to #59 

out_opensearch: Handle suppress_type_name operation correctly

---

README.md
lib/fluent/plugin/out_opensearch.rb

Closes https://github.com/fluent/fluent-plugin-opensearch/issues/24
Closes #46 
For stable retrieving AWS credentials, we should obtain AWS credentials on every requests.

Expire AWS credentials with a certain interval

---

fluent-plugin-opensearch.gemspec

opensearch-transport 2.0.1 and 1.0.1 unlocks using faraday 2.x but
fluent-plugin-opensearch isn't ready for it, as a result out_opensearch
doesn't work on newly install.
Fix #70
Signed-off-by: Takuro Ashie <ashie@clear-code.com>
DESCRIPTION HERE

Use faraday 1.x explicitly

---

README.md
lib/fluent/plugin/out_opensearch.rb
test/plugin/test_out_opensearch.rb

This PR makes to be able to handle OpenSearch serverless service in this plugin.

out_opensearch: Provide service_name choices for handling serverless

---

.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml

* Add Ruby 3.1 tasks
* Remove Ruby 2.6 tasks

Adjust GitHub workflows

---

README.OpenSearchInput.md

It just fixes a broken pointer in the documentation

Fix link to opensearch-ruby

---

.github/workflows/coverage.yaml
fluent-plugin-opensearch.gemspec

faraday_middleware-aws-sigv4 v0.6.1 is the final version to work with faraday v1.

Add a constraint for dependent gem

---

.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml
lib/fluent/plugin/opensearch_index_template.rb

Replace obsolete `File.exists?` with `File.exist?` to support Ruby 3.2

Support Ruby 3.2

---

.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml
fluent-plugin-opensearch.gemspec
lib/fluent/plugin/in_opensearch.rb
lib/fluent/plugin/out_opensearch.rb

Load Faraday v2 instead of v1

---

lib/fluent/plugin/out_opensearch.rb
test/plugin/test_out_opensearch.rb

Pass a value of refresh_credentials_interval as duration_seconds

---

lib/fluent/plugin/out_opensearch.rb
test/plugin/test_out_opensearch.rb

This reverts commit 17e2c49ba5bf336927e806f39e3873ac15b0fdae, reversing changes made to 66012d97be06cdf9b0f492a5d717f9db5a43e549.
This is because duration second should not be set up by default value. Duration second should be user/account dependent.
DESCRIPTION HERE

Revert "Merge pull request #78 from fluent/pass-credentials-duration"

---

test/helper.rb

Fix broken tests: https://github.com/fluent/fluent-plugin-opensearch/pull/109#issuecomment-1682061788

test: remove minitest to correct misjudge of the framework by flexmock

---

README.md
lib/fluent/plugin/out_opensearch_data_stream.rb
test/plugin/test_out_opensearch_data_stream.rb

- Add tag_key to record and remove keys if config options are set.
- Fix issue #83.
- Fix typo/language in README related to contributions.
Details
I've added test cases; however, when I try to run them locally I get the error included below. This happens for all test that include datastreams
`Fluent::ConfigError: Failed to create data stream: <foo> unknown keyword: acknowledged`
- [  ] tests passing

Add logic to write method of out_opensearch_data_stream

---

fluent-plugin-opensearch.gemspec

Since opensearch-ruby recently adapted semantic versioning, we can pin the dependency to 3.0.1.
This Version includes a fix to https://github.com/opensearch-project/opensearch-ruby/issues/205
This will solve #115 and possibly #98

pin dependency opensearch-ruby to 3.0.1

---

README.OpenSearchInput.md
lib/fluent/plugin/in_opensearch.rb
test/plugin/test_in_opensearch.rb

**Problem**: 
If there are two servers in the hosts field (example: hosts "server1:9200,server2:9200"), automatic switching to the available host does not work. If server1 is unavailable, it does not switch to server2, and the service writes an error and freezes:
"Unexpected error raised. Stopping the timer. title=:in_opensearch_timer error_class=Faraday::ConnectionFailed error="EOFError (EOFError)""
**Solution**:
I added a retry logic in case of connection failures. 
I created a service availability check function for high availability. New function get_reachable_hosts in in_opensearch.rb
I used one library opensearch to solve this problem.
And added ignoring any clear_scroll errors.

Added a retry logic and a service availability check function for high availability.

---

lib/fluent/plugin/out_opensearch_data_stream.rb

Due to some reason the body could be empty which results in infinite jumps between failed buffer flushes. Opensearch returns a 400 with "request body is required".

out_opensearch_data_stream: Early return on empty body

---

.github/workflows/linux.yml

This commit attempts to fix the GitHub Actions failure in [PR #142](https://github.com/fluent/fluent-plugin-opensearch/pull/142).
Ruby 3.2 Unit Testing on ubuntu-latest
```
The installation path is insecure. Bundler cannot continue.
/opt/hostedtoolcache/Ruby/3.2.5/x64/lib/ruby/gems/3.2.0/gems is world-writable (without sticky bit).
Bundler cannot safely replace gems in world-writable directories due to potential vulnerabilities.
Please change the permissions of this directory or choose a different install path.
Error: Process completed with exit code 38.
```
The last commit to the main branch was successful, but it was 5 months ago (Apr 30). It seems that an update to Ruby or Bundler may have broken the Action.
Based on my testing in my repository, this fix resolves the issue: [PR …

Fix bundle installation error on GitHub Action

---

lib/fluent/plugin/out_opensearch.rb
test/plugin/test_out_opensearch.rb

If `aws_credentials()` fails due to an unstable network or other issues, it throws an exception. This stops `timer_execute()` from repeating its block, preventing `OpenSearchOutput` from updating `@_aws_credentials`. As a result, `@_aws_credentials` will expire.
This commit catches the exception and prevents it from propagating to `timer_execute()`, ensuring continuous credential updates.

Prevent AWS credentials refresh from stopping on exception
